### ISSUE TITLE
experimental results

### ISSUE THREAD

**Issue by chalth** [fukexue/RGM#1]
In your experimental comparison,  there is a big difference between the results of Deep GMR and those of his paper.Do you know the reason?

**Comment by fukexue** [comment]
First, deepgmr only did clean and noise experiments on modelnet.From these two experimental results, we can see that the experimental results reported in this paper are similar to those reported in the original report. This can be observed in our CCD and RMSE provided by the author.Secondly, the author did not do the partial overlap experiment on modelnet.From the results of clean, deepgmr in the case of clean performance is very strong.
