### ISSUE TITLE
RuntimeError: Error building extension 'sparse_dot'

### ISSUE THREAD

**Issue by yao143** [fukexue/RGM#10]
hi, I get this error, who can help me ? thanks!!!

-----------------------------------------------------------------------------
(pytorch1.2) C:\Users\13\Desktop\RGM\RGM>python eval.py --cfg experiments/test_RGM_Seen_Jitter_shapenet_transformer.yaml
Traceback (most recent call last):
  File "C:\Anaconda\envs\pytorch1.2\lib\site-packages\torch\utils\cpp_extension.py", line 960, in _build_extension_module
    check=True)
  File "C:\Anaconda\envs\pytorch1.2\lib\subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "eval.py", line 13, in <module>
    from parallel import DataParallel
  File "C:\Users\13\Desktop\RGM\RGM\parallel\__init__.py", line 1, in <module>
    from .data_parallel import *
  File "C:\Users\13\Desktop\RGM\RGM\parallel\data_parallel.py", line 7, in <module>
    from .scatter_gather import scatter_kwargs, gather
  File "C:\Users\13\Desktop\RGM\RGM\parallel\scatter_gather.py", line 3, in <module>
    from sparse_torch import CSRMatrix3d, CSCMatrix3d, concatenate
  File "C:\Users\13\Desktop\RGM\RGM\sparse_torch\__init__.py", line 5, in <module>
    from .csx_matrix import CSRMatrix3d, CSCMatrix3d, dot, concatenate
  File "C:\Users\13\Desktop\RGM\RGM\sparse_torch\csx_matrix.py", line 13, in <module>
    '/usr/include/python{}.{}/'.format(sys.version_info.major, sys.version_info.minor)]
  File "C:\Anaconda\envs\pytorch1.2\lib\site-packages\torch\utils\cpp_extension.py", line 658, in load
    is_python_module)
  File "C:\Anaconda\envs\pytorch1.2\lib\site-packages\torch\utils\cpp_extension.py", line 827, in _jit_compile
    with_cuda=with_cuda)
  File "C:\Anaconda\envs\pytorch1.2\lib\site-packages\torch\utils\cpp_extension.py", line 880, in _write_ninja_file_and_build
    _build_extension_module(name, build_directory, verbose)
  File "C:\Anaconda\envs\pytorch1.2\lib\site-packages\torch\utils\cpp_extension.py", line 973, in _build_extension_module
    raise RuntimeError(message)
RuntimeError: Error building extension 'sparse_dot': [1/2] cl /showIncludes -DTORCH_EXTENSION_NAME=sparse_dot -DTORCH_API_INCLUDE_EXTENSION_H -IC:\usr\include\python3.6 -IC:\Anaconda\envs\pytorch1.2\lib\site-packages\torch\include -IC:\Anaconda\envs\pytorch1.2\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Anaconda\envs\pytorch1.2\lib\site-packages\torch\include\TH -IC:\Anaconda\envs\pytorch1.2\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDAv10.0\include" -IC:\Anaconda\envs\pytorch1.2\Include -D_GLIBCXX_USE_CXX11_ABI=0 /MD /wd4819 /EHsc -c C:\Users\13\Desktop\RGM\RGM\extension\sparse_dot\sparse_dot.cpp /Fosparse_dot.o
FAILED: sparse_dot.o
cl /showIncludes -DTORCH_EXTENSION_NAME=sparse_dot -DTORCH_API_INCLUDE_EXTENSION_H -IC:\usr\include\python3.6 -IC:\Anaconda\envs\pytorch1.2\lib\site-packages\torch\include -IC:\Anaconda\envs\pytorch1.2\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Anaconda\envs\pytorch1.2\lib\site-packages\torch\include\TH -IC:\Anaconda\envs\pytorch1.2\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDAv10.0\include" -IC:\Anaconda\envs\pytorch1.2\Include -D_GLIBCXX_USE_CXX11_ABI=0 /MD /wd4819 /EHsc -c C:\Users\13\Desktop\RGM\RGM\extension\sparse_dot\sparse_dot.cpp /Fosparse_dot.o
用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.16.27045 版
版权所有(C) Microsoft Corporation。保留所有权利。

注意: 包含文件:  C:\Anaconda\envs\pytorch1.2\lib\site-packages\torch\include\torch\csrc\api\include\torch/torch.h
注意: 包含文件:   C:\Anaconda\envs\pytorch1.2\lib\site-packages\torch\include\torch\csrc\api\include\torch/all.h
注意: 包含文件:    C:\Anaconda\envs\pytorch1.2\lib\site-packages\torch\include\torch\csrc\api\include\torch/cuda.h
注意: 包含文件:     C:\Anaconda\envs\pytorch1.2\lib\site-packages\torch\include\torch/csrc/WindowsTorchApiMacro.h
注意: 包含文件:      C:\Anaconda\envs\pytorch1.2\lib\site-packages\torch\include\c10/macros/Export.h
注意: 包含文件:       C:\Anaconda\envs\pytorch1.2\lib\site-packages\torch\include\c10/macros/cmake_macros.h
C:\Anaconda\envs\pytorch1.2\lib\site-packages\torch\include\torch\csrc\api\include\torch/cuda.h(5): fatal error C1083: 无法打开包括文件: “cstddef”: No such file or directory
ninja: build stopped: subcommand failed.

-----------------------------------------------------------
Prompt me "Error building extension'sparse_dot'"

**Comment by ZhileiChen99** [comment]
Do you have more than one GPUs? If you have only one GPU, you can try to remove all codes with respect to DataParallel.

**Comment by yao143** [comment]
Yes, I only have one GPU. Can you talk in more detail? Thank you very much

**Comment by ZhileiChen99** [comment]
You can first try to delete "from parallel import DataParallel", and then delete any codes with respect to this code. I am not sure this will work. Good luck.

**Comment by yao143** [comment]
Thank you very much! ! !
I tried it before you answered, and I can get the evaluation result.
