### ISSUE TITLE
about reqiurements.txt

### ISSUE THREAD

**Issue by oceans-penguin** [fukexue/RGM#11]
![image](https://user-images.githubusercontent.com/81892455/161719765-2aa0eb33-2a78-4ace-a392-6325e9978ace.png)

**Comment by fukexue** [comment]
you can solve this problem as follow:
git clone https://github.com/peter0749/etw_pytorch_utils.git
cd etw_pytorch_utils
python setup.py install

**Comment by fukexue** [comment]
.
