### ISSUE TITLE
About configurations and the visualization

### ISSUE THREAD

**Issue by Zayes** [fukexue/RGM#2]
Thanks for your great work! While I meet some difficulties during training. 
When I was trying to train the RGM model on seen/unseen crop ModelNet40 dataset with transformer, I got the "file not found" error because of the start epoch "123" in the .ymal file. I want to know if I set it to zero, will I achieve the results as you mentioned in the paper.
By the way, you have provided "draw_figures.py" to visualize the point cloud registration results. While it feels like not used in your experiments. Can you release the whole codes with your visualization?
I will appreciate it if you can solve my problems.

**Comment by fukexue** [comment]
Yes, you can set the start epoch to zero. You will be able to get results like the paper.
About draw_figures.py, this is what I used in the test. I'll add it to the demo later.

**Comment by liu-zikang** [comment]
hello，could you tell me how to run draw_figures.py? I want to visualize the point cloud registration results,but it seems that i can't make it, i'm looking forward to your reply!
