### ISSUE TITLE
No matching distribution found for etw-pytorch-utils==1.1.1

### ISSUE THREAD

**Issue by amgoing** [fukexue/RGM#4]
我在使用pip install -r requirements.txt这个语句的时候，报错说No matching distribution found for etw-pytorch-utils==1.1.1，我安装torch时使用的是这条语句
![图片](https://user-images.githubusercontent.com/39852388/125718069-6b616998-d15e-4405-8e21-3c9bb3bbe7b8.png)
为什么会这样呢，我的CUDA安装的是10.2的版本，cudnn安装的是7.6的版本，这样会有问题吗

**Comment by fukexue** [comment]
The reason may be that the library is not found in pip. However, if this library is not installed, it should not affect the operation of the program. If you must install it, you can try this operation `pip install git+git@github.com:chenzhutian/etw_pytorch_utils.git`, and remove etw-pytorch-utils==1.1.1 from the requirements file.

**Comment by amgoing** [comment]
好的，谢谢~



p.xie
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fukexue/RGM"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月15日(星期四) 上午10:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fukexue/RGM] No matching distribution found for etw-pytorch-utils==1.1.1 (#4)





 
The reason may be that the library is not found in pip. However, if this library is not installed, it should not affect the operation of the program. If you must install it, you can try this operation pip install ***@***.***:chenzhutian/etw_pytorch_utils.git, and remove ext from the requirements file.
