### ISSUE TITLE
有个可视化的问题请教一下

### ISSUE THREAD

**Issue by Allfu** [fukexue/RGM#5]
大佬好，感谢分享这么优秀的工作：
我刚接触点云配准没多久，正在尝试复现这个工程，想可视化看一下效果，目前通过导出pcb文件使用CloudCompare软件进行了初步的可视化，但是不能找到RT矩阵和pcb文件的对应关系，以至于看不到确切的配准效果。
有两个问题请教下：
1.请问在eval阶段，生成batch的时候是按顺序的么（第一个batch中的第一个tensor对应的是第一对数据的R/T矩阵么？）
2.这种通过导出pcb文件进行可视化正确么？
再次感谢分享！

**Comment by fukexue** [comment]
关于这个问题，是按照顺序生成的。
使用cloudcompare没有找到正确的对应关系可能是因为变换的计算方式，对一个点云进行变换有两种表达：
1、y=Rx+t
2、y=R(x+t)
这两种表达是不同的，建议使用一致的表达之后再进行可视化

**Comment by Allfu** [comment]
好的，谢谢大佬解惑！
