### ISSUE TITLE
CUDA / torch version?

### ISSUE THREAD

**Issue by mrcfschr** [fukexue/RGM#6]
Hi there,
thank you so much for sharing this awesome project! 
I'm new to deep learning. I'm curious to try out your code but I couldn't get it to work following the instruction in the readme. 
In the docs, https://pytorch.org/get-started/previous-versions/#v120, it says the PyTorch 1.2.0 binaries and wheels are built with CUDA9.2 and CUDA10.0. However, in your readme, it says to use CUDA10.2. Maybe this particular version doesn't matter but just following the readme I get a lot of errors and I'm not quite sure where I'm going wrong.  I'm a bit confused about how to set up the environment to be able to test the code. I tried many different versions of different dependencies but I still always get errors when I train.
I'll debug more and post the logs and steps to replicate if I can't solve the issue but just thought I post already now in case someone else has had similar problems with setting up the environment and might be able to help out.

**Comment by mrcfschr** [comment]
Never mind I was using windows, it works perfectly fine on Linux.

**Comment by fukexue** [comment]
I just saw it. I'm glad you solved this problem.
