### ISSUE TITLE
请教一下关于edge generator的问题

### ISSUE THREAD

**Issue by guoxinXiong** [fukexue/RGM#8]
大佬你好，感谢分享这么优秀的工作：
       我想请问一下代码里的生成边和邻接矩阵那里的问题，文章里写的是先由节点特征经过transformer后得到embedding特征，再由embedding特征点击加softmax生成邻接矩阵，但是代码里是使用DGCNN对点云提取了节点和边特征，把节点和边一起concat了之后放入transformer得到embedding，这里我不太明白为什么要这样做，希望大佬有空看到能讲解一下，感激不尽

**Comment by fukexue** [comment]
First of all, thank you very much for your attention to our work. We first use dgcnn to extract the primary features of point cloud, which is not good for direct registration. We hope to find the overlap between the two point clouds before further extracting point features. In the feature aggregation stage, the overlapping part only aggregates the features of the overlapping part without considering the features of the non overlapping part. Therefore, they need to be put into the transformer for learning to get the overlapping area score between the two point clouds.

**Comment by guoxinXiong** [comment]
非常抱歉大佬你第二天就回复了我，然而我却没有及时看你的回复，在此道歉
我可能没能看懂你的回复或者没有说把问题描述清楚，我迷惑的地方在于看一些关于图的操作时，我的理解是生成边E是用节点N两两之间做一些运算来得到的，然后每条边Econcat到一起组成邻接矩阵，这个过程应该是只靠节点N来参与计算的，而大佬代码里感觉是DGCNN得到节点N和边E，然后再生成边E，我能理解你的回复中说重复的区域那种操作是为了这样能生成更好的边E吗？
这个问题可能有点蠢，希望大佬不要介意，对大佬的感激不尽
如果能分享一些图操作的基础的帖子就更好了，谢谢大佬

**Comment by fukexue** [comment]
yes
