### ISSUE TITLE
issues about correspondSlover.py

### ISSUE THREAD

**Issue by ZhileiChen99** [fukexue/RGM#9]
When I try to train the clean seen model on Modelnet40, the program has some errors, which appear in the line67, "assert torch.all(torch.det(R) > 0)", hope for your answer.

**Comment by ZhileiChen99** [comment]
I find some elements are nan in the return of torch.det(R)

**Comment by yao143** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
